/********** PLANTS ACTION TYPES *************** */

export const FETCH_PLANETS_STARTED = "FETCH_PLANETS_STARTED";
export const FETCH_PLANETS_END = "FETCH_PLANETS_END";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";

export const FETCH_FILMS_STARTED = "FETCH_FILMS_STARTED";
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";
export const FETCH_FILMS_SUCCES = "FETCH_FILMS_SUCCES";
